/**
 * Dev/test seed data for the in-memory backend. Mirrors the catalog rows
 * deployed by migrations 002 + 006 so `VOXELPLUS_DATA_BACKEND=memory` (or
 * `npm run dev` with no Supabase env) produces a working product surface.
 * Keep in sync with the migrations.
 */
export const DEV_SEED: Record<string, any[]> = {
  voxel_cosmetics: [
    { id: 'cosmetic_dirt_block', enabled: true,       name: 'Dirt Block',       type: 'featured',   icon: '🟫', rarity: 'common',    description: 'A humble beginning.',                          unlock_condition: 'Rewarded ads' },
    { id: 'cosmetic_grass_block', enabled: true,      name: 'Grass Block',      type: 'featured',   icon: '🟩', rarity: 'common',    description: 'The surface of the world.',                     unlock_condition: 'Rewarded ads' },
    { id: 'cosmetic_crafting_table', enabled: true,   name: 'Crafting Table',   type: 'featured',   icon: '📦', rarity: 'common',    description: 'Where creations begin.',                       unlock_condition: 'Rewarded ads' },
    { id: 'cosmetic_compass', enabled: true,          name: 'Compass',          type: 'featured',   icon: '🧭', rarity: 'rare',      description: 'Points toward adventure.',                     unlock_condition: 'Rewarded ads' },
    { id: 'cosmetic_chest', enabled: true,            name: 'Chest',            type: 'featured',   icon: '🗃️', rarity: 'rare',      description: "A collector's pride.",                         unlock_condition: 'Rewarded ads' },
    { id: 'cosmetic_diamond', enabled: true,          name: 'Diamond',          type: 'featured',   icon: '💎', rarity: 'epic',      description: 'The rarest of treasures.',                     unlock_condition: 'Publish your first Voxel+ pack' },
    { id: 'cosmetic_netherite', enabled: true,        name: 'Netherite Ingot',  type: 'featured',   icon: '⬛', rarity: 'epic',      description: 'Forged in the Nether.',                        unlock_condition: 'Use Voxel+ on multiple MC versions' },
    { id: 'cosmetic_emerald', enabled: true,          name: 'Emerald',          type: 'featured',   icon: '💚', rarity: 'rare',      description: "A merchant's currency.",                       unlock_condition: 'Rewarded ads' },
    { id: 'cosmetic_nether_star', enabled: true,      name: 'Nether Star',      type: 'featured',   icon: '⭐', rarity: 'legendary', description: 'The rarest cosmetic.',                       unlock_condition: 'Reserved for Voxel+ Founders' },
    { id: 'cosmetic_ender_dragon_egg', enabled: true, name: 'Dragon Egg',       type: 'featured',   icon: '🥚', rarity: 'legendary', description: 'The ultimate trophy.',                       unlock_condition: 'Reserved for Voxel+ Team' },
    { id: 'cosmetic_beacon', enabled: true,           name: 'Beacon',           type: 'featured',   icon: '🔷', rarity: 'legendary', description: 'A beacon of light.',                         unlock_condition: 'Achievement unlocked' },
    { id: 'cosmetic_totem', enabled: true,            name: 'Totem of Undying', type: 'featured',   icon: '🪄', rarity: 'epic',      description: 'Cheating death.',                              unlock_condition: 'Achievement unlocked' },
    { id: 'cosmetic_book', enabled: true,             name: 'Enchanted Book',   type: 'badge_icon', icon: '📕', rarity: 'common',    description: 'Knowledge is power.',                          unlock_condition: 'Achievement unlocked' },
    { id: 'cosmetic_sword', enabled: true,            name: 'Diamond Sword',    type: 'badge_icon', icon: '⚔️', rarity: 'rare',      description: 'Ready for battle.',                            unlock_condition: 'Achievement unlocked' },
    { id: 'cosmetic_elytra_x', enabled: true,         name: 'Elytra',           type: 'featured',   icon: '🪽', rarity: 'legendary', description: 'Wings of the End.',                            unlock_condition: 'Achievement unlocked' },
    { id: 'effect_enchanted_glint', enabled: true,    name: 'Enchanted Glint',  type: 'effect',     icon: '✨', rarity: 'rare',      description: 'A shimmering enchantment aura.',               unlock_condition: 'Rewarded ads' },
    { id: 'effect_golden_radiance', enabled: true,    name: 'Golden Radiance',  type: 'effect',     icon: '🌟', rarity: 'epic',      description: 'Bathed in golden light.',                      unlock_condition: 'Rewarded ads' },
    { id: 'effect_prismatic_shimmer', enabled: true,  name: 'Prismatic Shimmer',type: 'effect',     icon: '🌈', rarity: 'legendary', description: 'A rainbow sheen worthy of the End.',           unlock_condition: 'Rewarded ads' },
    { id: 'effect_smoldering_ember', enabled: true,   name: 'Smoldering Ember', type: 'effect',     icon: '🔥', rarity: 'epic',      description: 'Nether-hot embers trail behind you.',          unlock_condition: 'Achievement unlocked' },
    { id: 'effect_frost_aura', enabled: true,         name: 'Frost Aura',       type: 'effect',     icon: '❄️', rarity: 'rare',      description: 'Cold as powdered snow.',                       unlock_condition: 'Achievement unlocked' }
  ],
  voxel_vpack_catalog: [
    { id: 'vpack_starter_survival', name: 'Starter Survival Pack', description: 'Essential mods and tweaks for a fresh survival world.', icon: '🎒', contents: '{"mods": true}', enabled: true },
    { id: 'vpack_builder_tools',    name: "Builder's Toolkit",     description: 'Block palettes and building helpers for megabuilds.',   icon: '🧱', contents: '{"mods": true}', enabled: true },
    { id: 'vpack_explorer_pack',    name: "Explorer's Bundle",     description: 'Waypoints, maps and traversal goodies.',                icon: '🗺️', contents: '{"mods": true}', enabled: true }
  ],
  voxel_titles: [
    { id: 'title_founder',          name: 'Founder',          description: 'Voxel+ Founder',              color: '#f59e0b' },
    { id: 'title_developer',        name: 'Developer',        description: 'Voxel+ Developer',            color: '#3b82f6' },
    { id: 'title_creator',          name: 'Creator',          description: 'Voxel+ Content Creator',      color: '#10b981' },
    { id: 'title_contributor',      name: 'Contributor',      description: 'Voxel+ Contributor',          color: '#8b5cf6' },
    { id: 'title_tester',           name: 'Beta Tester',      description: 'Voxel+ Beta Tester',          color: '#6366f1' },
    { id: 'title_moderator',        name: 'Moderator',        description: 'Voxel+ Moderator',            color: '#ef4444' },
    { id: 'title_community',        name: 'Community',        description: 'Community Member',            color: '#6b7280' },
    { id: 'title_featured_creator', name: 'Featured Creator', description: 'Featured Voxel+ Creator',     color: '#f59e0b' },
    { id: 'title_voxelplus_team',   name: 'Voxel+ Team',      description: 'Official Voxel+ Team Member', color: '#3b82f6' },
    { id: 'title_early_supporter',  name: 'Early Supporter',  description: 'Early Voxel+ Supporter',      color: '#a78bfa' }
  ],
  voxel_badges: [
    { id: 'badge_verified',     name: 'Verified',     description: 'Verified Voxel+ Account',      icon: '✅' },
    { id: 'badge_developer',    name: 'Developer',    description: 'Voxel+ Developer',             icon: '🛠' },
    { id: 'badge_creator',      name: 'Creator',      description: 'Content Creator',              icon: '⚒' },
    { id: 'badge_beta_tester',  name: 'Beta Tester',  description: 'Voxel+ Beta Tester',           icon: '🧪' },
    { id: 'badge_featured',     name: 'Featured',     description: 'Featured by the Voxel+ Team',  icon: '⭐' },
    { id: 'badge_founder',      name: 'Founder',      description: 'Voxel+ Founder',               icon: '👑' },
    { id: 'badge_community',    name: 'Community',    description: 'Active Community Member',      icon: '💬' },
    { id: 'badge_event_winner', name: 'Event Winner', description: 'Voxel+ Event Winner',          icon: '🏆' }
  ],
  voxel_achievements: [
    { id: 'achievement_first_instance',   title: 'First Steps',        description: 'Create your first Minecraft instance.',               icon: '🌱', requirement: 'Create 1 instance',    condition_type: 'instances_total',   condition_value: 1,  category: 'instances', rarity: 'common',    hidden: false, reward_cosmetic_id: 'cosmetic_crafting_table',   reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_instance_3',       title: 'Settler',            description: 'Create 3 Minecraft instances.',                       icon: '🏘️', requirement: 'Create 3 instances',   condition_type: 'instances_total',   condition_value: 3,  category: 'instances', rarity: 'common',    hidden: false, reward_cosmetic_id: 'cosmetic_compass',         reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_instance_5',       title: 'Town Planner',       description: 'Create 5 Minecraft instances.',                       icon: '🏗️', requirement: 'Create 5 instances',   condition_type: 'instances_total',   condition_value: 5,  category: 'instances', rarity: 'rare',      hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: 'badge_community', enabled: true },
    { id: 'achievement_instance_10',      title: 'World Builder',      description: 'Create 10 Minecraft instances.',                      icon: '🌍', requirement: 'Create 10 instances',  condition_type: 'instances_total',   condition_value: 10, category: 'instances', rarity: 'epic',      hidden: false, reward_cosmetic_id: 'cosmetic_totem',           reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_instance_25',      title: 'Dimension Architect',description: 'Create 25 Minecraft instances.',                      icon: '🏛️', requirement: 'Create 25 instances',  condition_type: 'instances_total',   condition_value: 25, category: 'instances', rarity: 'legendary', hidden: false, reward_cosmetic_id: 'cosmetic_beacon',          reward_title_id: 'title_creator',         reward_badge_id: null,              enabled: true },
    { id: 'achievement_cosmetic_1',       title: 'First Flair',        description: 'Own your first cosmetic.',                            icon: '🎨', requirement: 'Own 1 cosmetic',       condition_type: 'cosmetics_owned',   condition_value: 1,  category: 'cosmetics', rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_cosmetic_3',       title: 'Stylist',            description: 'Own 3 cosmetics.',                                    icon: '🧥', requirement: 'Own 3 cosmetics',      condition_type: 'cosmetics_owned',   condition_value: 3,  category: 'cosmetics', rarity: 'common',    hidden: false, reward_cosmetic_id: 'cosmetic_book',            reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_cosmetic_5',       title: 'Collector',          description: 'Own 5 cosmetics.',                                    icon: '🗃️', requirement: 'Own 5 cosmetics',      condition_type: 'cosmetics_owned',   condition_value: 5,  category: 'cosmetics', rarity: 'rare',      hidden: false, reward_cosmetic_id: 'cosmetic_chest',           reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_cosmetic_10',      title: 'Curator',            description: 'Own 10 cosmetics.',                                   icon: '💎', requirement: 'Own 10 cosmetics',     condition_type: 'cosmetics_owned',   condition_value: 10, category: 'cosmetics', rarity: 'epic',      hidden: false, reward_cosmetic_id: 'cosmetic_diamond',         reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_cosmetic_25',      title: 'Vault Keeper',       description: 'Own 25 cosmetics.',                                   icon: '👑', requirement: 'Own 25 cosmetics',     condition_type: 'cosmetics_owned',   condition_value: 25, category: 'cosmetics', rarity: 'legendary', hidden: false, reward_cosmetic_id: 'cosmetic_ender_dragon_egg',reward_title_id: 'title_featured_creator',reward_badge_id: null,              enabled: true },
    { id: 'achievement_effect_1',         title: 'First Sparkle',      description: 'Own your first cosmetic effect.',                     icon: '✨', requirement: 'Own 1 effect',         condition_type: 'effects_owned',     condition_value: 1,  category: 'cosmetics', rarity: 'common',    hidden: false, reward_cosmetic_id: 'effect_frost_aura',        reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_effect_3',         title: 'Radiant',            description: 'Own 3 cosmetic effects.',                             icon: '🌟', requirement: 'Own 3 effects',        condition_type: 'effects_owned',     condition_value: 3,  category: 'cosmetics', rarity: 'rare',      hidden: false, reward_cosmetic_id: 'effect_smoldering_ember', reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_effect_5',         title: 'Prismatic',          description: 'Own 5 cosmetic effects.',                             icon: '🌈', requirement: 'Own 5 effects',        condition_type: 'effects_owned',     condition_value: 5,  category: 'cosmetics', rarity: 'epic',      hidden: false, reward_cosmetic_id: 'cosmetic_sword',          reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_vpack_1',          title: 'Packer',             description: 'Create your first VPack.',                            icon: '📦', requirement: 'Create 1 VPack',       condition_type: 'vpacks_created',    condition_value: 1,  category: 'vpacks',    rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_vpack_3',          title: 'Pack Rat',           description: 'Create 3 VPacks.',                                    icon: '📦', requirement: 'Create 3 VPacks',      condition_type: 'vpacks_created',    condition_value: 3,  category: 'vpacks',    rarity: 'common',    hidden: false, reward_cosmetic_id: 'cosmetic_emerald',        reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_vpack_5',          title: 'Pack Master',        description: 'Create 5 VPacks.',                                    icon: '📦', requirement: 'Create 5 VPacks',      condition_type: 'vpacks_created',    condition_value: 5,  category: 'vpacks',    rarity: 'rare',      hidden: false, reward_cosmetic_id: null,                      reward_title_id: 'title_early_supporter', reward_badge_id: null,              enabled: true },
    { id: 'achievement_vpi_1',            title: 'Installer',          description: 'Install your first VPack.',                           icon: '⬇️', requirement: 'Install 1 VPack',      condition_type: 'vpacks_installed',  condition_value: 1,  category: 'vpacks',    rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_vpi_3',            title: 'Modular Mind',       description: 'Install 3 VPacks.',                                   icon: '⬇️', requirement: 'Install 3 VPacks',     condition_type: 'vpacks_installed',  condition_value: 3,  category: 'vpacks',    rarity: 'common',    hidden: false, reward_cosmetic_id: 'effect_frost_aura',        reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_vpi_5',            title: 'Full Stack',         description: 'Install 5 VPacks.',                                   icon: '⬇️', requirement: 'Install 5 VPacks',     condition_type: 'vpacks_installed',  condition_value: 5,  category: 'vpacks',    rarity: 'rare',      hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: 'badge_tester',    enabled: true },
    { id: 'achievement_conversion_1',     title: 'Archiver',           description: 'Convert an instance into a VPack.',                   icon: '🗜️', requirement: 'Convert 1 instance',   condition_type: 'vpacks_converted',  condition_value: 1,  category: 'vpacks',    rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_version_1',        title: 'Version Hopper',     description: 'Create an instance on your first MC version.',        icon: '🧭', requirement: 'Use 1 MC version',     condition_type: 'versions_distinct', condition_value: 1,  category: 'minecraft', rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_version_3',        title: 'Time Traveler',      description: 'Create instances on 3 distinct MC versions.',         icon: '⏳', requirement: 'Use 3 MC versions',    condition_type: 'versions_distinct', condition_value: 3,  category: 'minecraft', rarity: 'rare',      hidden: false, reward_cosmetic_id: 'cosmetic_netherite',      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_library_10',       title: 'Archivist',          description: 'Save 10 pieces of content to your library.',          icon: '📚', requirement: 'Save 10 items',        condition_type: 'library_total',     condition_value: 10, category: 'library',   rarity: 'rare',      hidden: false, reward_cosmetic_id: 'cosmetic_book',            reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_first_mod',        title: 'Modded',             description: 'Install your first mod via Voxel+.',                  icon: '🔧', requirement: 'Install 1 mod',        condition_type: 'mods_installed',    condition_value: 1,  category: 'minecraft', rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_shader_1',         title: 'Shaded',             description: 'Install your first shader pack.',                     icon: '💡', requirement: 'Install 1 shader',     condition_type: 'shaders_installed', condition_value: 1,  category: 'minecraft', rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_pack_public_1',    title: 'Published',          description: 'Publish a public pack to your library.',              icon: '🚀', requirement: 'Publish 1 pack',       condition_type: 'packs_public',      condition_value: 1,  category: 'library',   rarity: 'epic',      hidden: false, reward_cosmetic_id: 'cosmetic_diamond',         reward_title_id: 'title_contributor',     reward_badge_id: null,              enabled: true },
    { id: 'achievement_profile_public',   title: 'Going Public',       description: 'Make your profile public.',                           icon: '💚', requirement: 'Set profile public',   condition_type: 'profile_public',    condition_value: 1,  category: 'profile',   rarity: 'common',    hidden: false, reward_cosmetic_id: 'cosmetic_emerald',        reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_profile_avatar',   title: 'Self Portrait',      description: 'Upload a custom profile avatar.',                     icon: '🖼️', requirement: 'Upload avatar',        condition_type: 'custom_avatar',     condition_value: 1,  category: 'profile',   rarity: 'common',    hidden: false, reward_cosmetic_id: null,                      reward_title_id: null,                    reward_badge_id: null,              enabled: true },
    { id: 'achievement_secret_legend',    title: 'Living Legend',      description: '???',                                                 icon: '🐲', requirement: 'Hidden achievement',   condition_type: 'legendary_owned',   condition_value: 1,  category: 'hidden',    rarity: 'secret',    hidden: true,  reward_cosmetic_id: 'cosmetic_nether_star',     reward_title_id: 'title_founder',         reward_badge_id: 'badge_founder',   enabled: true },
    { id: 'achievement_secret_converter', title: 'Bulk Archiver',      description: '???',                                                 icon: '🗜️', requirement: 'Hidden achievement',   condition_type: 'vpacks_converted',  condition_value: 5,  category: 'hidden',    rarity: 'secret',    hidden: true,  reward_cosmetic_id: 'cosmetic_elytra_x',        reward_title_id: null,                    reward_badge_id: null,              enabled: true }
  ]
};
