// Official Minecraft 1.21.1 Item Textures — 48 items
// Source: InventivetalentDev/minecraft-assets (MIT license)
// Auto-generated by scripts/download-textures.js

export interface MinecraftItemDef {
  id: string;
  name: string;
  category: 'blocks' | 'items' | 'combat' | 'tools' | 'redstone';
  dataUrl: string;
}

export const MINECRAFT_ITEMS: MinecraftItemDef[] = [
  {
    "id": "minecraft:grass_block",
    "name": "Grass Block",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAeFBMVEWcy2yXxmeTwmOSwWKQv2CNvF2KuVp/v1V+vlSDslOBsFF2tkx1tUt0tEpzs0lxsUdwsEa5hVxvr0VtrUNsrEJrq0FqqkBpqT9oqD5npz2Hh4dmpjxkpDpiojhhoTdgoDZfnzVXly2WbEpQkCZsbGx0WER5VTpZPSnN78OwAAAAnElEQVR42jWNCw7CMAxDw/8/CBuMbTBGGPb9b4hbQRtZT3Gfaodd0XXnoVrvrk3dv0vbV8vthrfHMJ0XfdVcbEG71zzxsJpN+HrSOJJHkgNLgoQFwhkQc0QQBkYISEADN1e2Ak+jyhKHlGDOsJS6FCNZhkg2oZMlLbIfdJfUwrKoZpRCjSnzBj8pKfgg1U6ZYYlAheP/ratuocjvvsNMH5BFYTKgAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:diamond",
    "name": "Diamond",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAIVBMVEUAAAD////V//ah++hK7dks4NggxbUaqqcckZoRcnoUXlN/hNeyAAAAAXRSTlMAQObYZgAAAF1JREFUeNpjwApmzoTQnIJCE8CMiS5GWWABEWNltwVghpCQC4gx0dHFuKwKxHByNm4DM8SMTdpBjEku5eVpXUAGl3taWtkCECM8La0YxGBY4WKcBTaZa9WqBUg2AwByXRcdUQ3W3QAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:nether_star",
    "name": "Nether Star",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEUAAAD9/6ja4uLg4nfL1ta5ycnS0gCIpKRkkJBVa2uOynhjAAAAAXRSTlMAQObYZgAAAEpJREFUeNpjwA4aoDRHJZTRrj4BwmgVhTA6SkQqQSyOUhcR10qQCkXBZMHwCSARV9NwsL6ZJaKVENVTxaHap7tDGZyVDFAwAdliAFlNENjnSBVaAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:redstone",
    "name": "Redstone Dust",
    "category": "redstone",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAGFBMVEUAAAD/AACqDwFyAABcBwBBBQA0BgUtAAChZ6iRAAAAAXRSTlMAQObYZgAAAElJREFUeNpjwA9YHKAMZxWogKJqAZjhJGQYDhZQUlR1BQk5C5kKB6WDZIyETENAcqWKykGhIBH2IFPXMLC28tSwcgYwKC/HaiEAtf4MFvnbFVwAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:command_block",
    "name": "Command Block",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAABACAMAAAAkowekAAAAY1BMVEXSz9rOy9bNytXFws3XtJ3orWSzsLnPpoufnafOj2bJj2uIrWTOeneRj5nChz7Hfk/zYFy7bTqsaWfIVFJ3dIBihz6bbDKmYDDNOjZObDKGQ0FvSSukLiuiLiyCJSNUPCRANCAzufVLAAAAr0lEQVR42uWSwRLCIAxEY61Li9aIVlFR4f+/0gTKmZvOKJfN29ObHYiZRz8y1yTNXq6apGnkGpckTWP6FFNOT5lNoG4djDbkvBVeARiksZ5YGuUnMAXrHTG7RChvSo6l4NhhjzsOmGPxSB3Km9PiEQbgJhyqhw0TlG310GZWLh5GGzFVNtlDfZzLhsXDC3NN+uwep8YeF+zwaOxx/qE9XmjvcW3ssf2jPTY4fvd/vAFdwTU+2g9lYgAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:golden_apple",
    "name": "Golden Apple",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEUAAAD+/+b2+JLq7lfsy0XbohOyZBF1KAJUJAlUEglKVtcNAAAAAXRSTlMAQObYZgAAAFxJREFUeNpjQAHsMEYGjFEAodjS2wvAdGBESjiIlWokKGRaDmIYGxs7h4MYzs4uzp5ARmmIa0gwmBEa6hocCTI21DXUdQKIkRrqEgZiMEwLS81kAAHO8soJSC4AAKL1E97Kij+BAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:elytra",
    "name": "Elytra",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAG1BMVEUAAACPj7OMjIx/f5hzc3Nwbo1paWlLS0s1NTXBGAVdAAAAAXRSTlMAQObYZgAAAGNJREFUeNptzbENgDAQA8DvnBY2ADaAMEEUMQAJE4BESUUoXYW1+VDnpbevs9QuPW/626VkVXAN0dhLMHZEO1DQT8TUK9xMrFZhPRGcYo9EXChyBxp/ikjeaI4Co5FZwPKV6Q9t5hZq0HxRVgAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:ender_pearl",
    "name": "Ender Pearl",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAIVBMVEUAAACM9OIszbE0mYglhHQbe2sQXlELTUIMNzAGOTEDJiC5a2thAAAAAXRSTlMAQObYZgAAAFtJREFUeNpjwAo4OqB0swmE1WyS5rIAJGAiVJ7mBWIYas4szwLJOM1aNb0MKLc4HchwAzKWgBhmQAaXe+XMIisGIMOtvFwRpJhhabozUAYktCxtFZACsVYh2wwA2BYa2KT1S0MAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:obsidian",
    "name": "Obsidian",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAD1BMVEU7J1QnHj0QDBwGAwsAAAFbDTSxAAAAaUlEQVR42gVAARGAMAj8mUA3AzhYAOUJoED/TB68Ut/xNLiFb9wVhfPpaybePs3KHJ+sqmRCVpCNBbG9+ekJvySq3hPVZI7qgl56aBihTmPph+Cyu4ng3kJ2vRSHMoQ+8FGHLU9o5FwkfyEoFb7iY82bAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:emerald",
    "name": "Emerald",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAIVBMVEUAAADb/+uv/c2C9q1B84QX3WIAqiwAlSkAexgAUwAALQC5+lfcAAAAAXRSTlMAQObYZgAAAENJREFUeNpjwApmzoTQnCKuE8CMiSpuUWABIRW31AUghmqQWhmUYdaGxgg2a4UyPEpBDIZpFe1WEAPTgTJgsGoVVpsBDRwS6h42ddsAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:beacon",
    "name": "Beacon",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEX////u///W//7E//7M7PCc8u1v49xJ1cwry8ArubCw6MYmAAAAY0lEQVR42mOAA86ZMzs6OmZOYeCc0dFe0dEJZHSUl5WXd0xh4GgvT0srr2gBMsqCTdOBDM72VCPlMBCjPFlRyCwdKFUGYpQDFUOkEIph2sEGlqeXd4AYICtADJClM4GWukABAJACLvlnO3vrAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:tnt",
    "name": "TNT",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEX////d2dnOzs6+srPqQxjbLxqRLRGxFSc3NlYbGjwg8AI1AAAATUlEQVR42mNwCYdAhtAyCMTHYBJUEhRSFBRgYOyY2KQp0anAIKyp1KGh2CjIwCQh2NihNMmQgVFTsUlTaaICgzEUMJSnQSA+k8vLIBAAaGUqJHBby+wAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:iron_sword",
    "name": "Iron Sword",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAi0lEQVQ4y2NgIAO4uLj8h2GyNMOAhITEf7I079u3j3QDqKb5xo0bNNKMLVRBfJAmomwGKc7OzoYbQpJmZEOmTZsGVgzSBGKT5GeYASAMcg3JAYbuFZI1e5qJ/s/wkwNrhAUq0YaANHemq//XkOMGawBphBlEMPRBGGQzTDMygBlE0M8k+xfdBnINAAA+k7meeyM0+AAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:totem_of_undying",
    "name": "Totem of Undying",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEUAAAD9++747qXq24TRp11B5n/Fh0IAu0agWyOFQA8RGs9sAAAAAXRSTlMAQObYZgAAAGZJREFUeNpjQAIcHR0NYEazsbEFmDFZUMkSzJjiZOIJZkwMcYwEM6YWqlaCGdOcTDLBmjuTzWYADeAwmeyWkpkygYFhZpOQscdMsIEuLplgxTM6OjrBDE63tAlQRgqEwTBzJgMDAwCBcRls3IDM1wAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:crafting_table",
    "name": "Crafting Table",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAANlBMVEX////Y2Ni1tbXCnWK4lF+vj1WfhE2WdEF+YjdnUCxzOSBLKxhBIw44IRYoHgsbFg0ZFAwRDggy6vjwAAAAlElEQVR42h2OQW7DQBDDKO04hdse+v9vtk1sxx4F2YsOIkBQP/8Jn5fIuIO+TeTaB4zNkjEk3Zu9C9EURZhIA06K57gA8+TrsTaFej0iY1h5H45DIPwxDSNM/ZJNmOLg1rQ5AE6M+/eM7eEbGBMRC0IypUuC9HZp7AvF1UGzY1w5PmaniRHRAoWUlgDNrUyWkVIEeQEDCkhYTUzCNgAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:bookshelf",
    "name": "Bookshelf",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAV1BMVEW1tbXMpmy8mGKzjFGomwqJiYmfhE2bd0J1jhGJfgh8Yj4Rjmtecg0xY6NVaAlpVDMxW44Ma1BJSUkqTnq8FhZ3MAc/Pz+RERFjKAVBMRo2KhUsIhMnHhFXZPHoAAAAo0lEQVR42gWAgUpCUQyGv22/x0iRoHr/1xNUoqsRHc+2UARGJDRgneITGoPGH/FyFt0UDpfdW0YjZdEBX8sKvqWZBjxOSABTDrGKm1YXiYswixp9ymbkeErXpsF+6RuGtESjZTQY8SfecWrzo1nhfRYzuI+ldO5+MKTr7gjAc7+0jb3mR0x4VbHgZy45BensMuEwNkVUjZwzRsjDUV5oMKMBg3/odFPa5sE2/wAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:dragon_egg",
    "name": "Dragon Egg",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUtATMQEBAICAxZr2Z4AAAATklEQVR42g3HMQ6AIBBFwVd7EzkOhYmUFibscSxI2E4SCPxT6nSDNEROcmxNMXdzZrCC++aUGpxRraH/SClQmonnujvRyiJmDby/4jy6Pj8UIWcnjtA6AAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:amethyst_shard",
    "name": "Amethyst Shard",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAGFBMVEUAAAD//dX+y+bPoPOzjvONasxvT6tUOYoaPFOGAAAAAXRSTlMAQObYZgAAAE5JREFUeNpjwA7Y0tIgjCQldYiAk6I5RMBFOBwsYOScCmakGJmmFoAEXAxT00ECqaEqYAGGspAQsABDeVlIAYSRHs4ABuylCQwQkIZqMQDBkg6s9kncBgAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:enchanted_book",
    "name": "Enchanted Book",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAPFBMVEUAAADW1ta3t7fTohbUlhqZmZlbW1ukLCtlSxfFEzmdGzeJISBUPhNSLhBEMxBsFxdEJQphFBQxIQQWEAV8/BcXAAAAAXRSTlMAQObYZgAAAG1JREFUeNp1z0EWgyAMBNA0NA0WwTG5/101Ik9dOLv5ZBbQa8zsWWvOlyxLzREbr6pTbi3kPJ7/0yUx7hIAOy5aiO4Vv5jwIZoShIXI64djhfRlFsMpgGgRgzt1EeZSeh2CskYdAvhKt7j76683mGkGwVjE2/sAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:heart_of_the_sea",
    "name": "Heart of the Sea",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAG1BMVEUAAAAdwtEflrEhgKEdbY0PWHUNSF8LOk0IIFSR1f/0AAAAAXRSTlMAQObYZgAAAGdJREFUeNpjQAYuLlDaSBnMYjFSUlJOADKcFYWUlM1gDHeIjJKxawEDizGQNnYpYGAPMTY2NnFtYGAvT3VxCesoYGAoKy+v6MhgADJSQ0PDKoAM9rTQ0PQGBiDoSC/vYGAAszqQnQAAU3AWMEUVqKkAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:diamond_sword",
    "name": "Diamond Sword",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAJFBMVEUAAAAOPzYIJSAz68uk/fArx6weincVY1VoTh5JNhUoHguJZycazUdMAAAAAXRSTlMAQObYZgAAAExJREFUGNN1jsENwDAMAgGndpLuv29/jZFa/+4QwkA/ks5jyPky8cHxwyQAxslZNAaYiux9Zlb4A0XjNcVu1r0hvYacGwB0Rq0OSC4ehwkBE0lygnsAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:diamond_pickaxe",
    "name": "Diamond Pickaxe",
    "category": "tools",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEUAAAAz68srx6wnspqJZydoTh5JNhUOPzYoHgsIJSBDqdTeAAAAAXRSTlMAQObYZgAAAEZJREFUeNpjwArKywvANLuQsXoqmFU509iDAQKSLCE0W4TRBDAjpWHyBIgAw+QJEAGGSRMgAgwTJ0AEGDihAlAtUEYHms0AO88PQ5cytswAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:netherite_sword",
    "name": "Netherite Sword",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAKlBMVEUAAACGe4ZwZ3BdVl1zRUNRRE5PPD5gNDI7OTtKKUAyJycvISIjEBIWCBTo6UOrAAAAAXRSTlMAQObYZgAAAFVJREFUeNpjgADOmVDGRBmogBCUMTHwAERAVQciMDkYJDCTgTMqB8ydMHXZAbACzawciEqlZQegSmMgNHdNFkRky4Eza0D0zB4GhjMgxiyoSoY7UAYAZfEWu0XQZ4wAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:netherite_ingot",
    "name": "Netherite Ingot",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAIVBMVEUAAABzcXNaV1pNSU1IRUhMQUM7OTs8MjIxKSonHB0RERGQLp7qAAAAAXRSTlMAQObYZgAAAGNJREFUeNpjwAFmQijOmaENYO4UZ9MIENfFSEnZpIFhUqipsZKSoAfDVCFl40BBjyyG6YVKgiIV7VkM09IE3Ts60oAiaW4dHWVVCxg4ytw7ylctYGBgaE/vWsUAAhxdC7DbCwDOnxpNtnrV5wAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:end_crystal",
    "name": "End Crystal",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAJFBMVEUAAAD5/f7cx+az2N3Pst2cvcG+ldSVTbviBifOBiRfJ323BSAEcNtzAAAAAXRSTlMAQObYZgAAAGxJREFUeNpjQABDQRAQYGAAogIGhgAQg10dwlhVpla1AMRYnuaWvsAAyChLaUkrADLE0zy2uGUBpcyUOjJb3BcwMISnuaW5VQWA1XSmFxiAdJW5lYN1rSp3rwIzGLiqGBiADFFj41BjYwO4IwAm7huJAJs/qwAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:trident",
    "name": "Trident",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAbUlEQVQ4y2NgoAeYNm3afxCgSPONGzfABoBoog3DpRkkTrQBZGsGgezs7P96cQH/0TUT7Q2Q5oi5fWBD0DWDDCfKAIfKTDBGdglRmsXcLcEaQTQIgzTBMNE2gzSSHO8wf480zWQHGCy6yNYMBACktqum4kbbjgAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:bow",
    "name": "Bow",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAaklEQVR42mNgoCfwNBP9j4xJ1tSZrv4/w08OjEFsDTnu/wQ1wjTBNCBjvJqzs7PBGrFpcHFxIax52rRpYBpdnnaaYQaAnE22ZlwhS1Azsu3oBhClGZcL6KMZm/NJ0oxuAMmaCcUA0YBczQDVGni1vuKfywAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:crossbow",
    "name": "Crossbow",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAARVBMVEX///+BgYGQWB9YWFhtQhhERERNLhEpKjcfEgYAAACXl5eWlpa1cy9tbW2QWB9tQhhERERNLhFIKxA7JA02IAsqGgkfEgZJrGHHAAAACnRSTlMAAAAAAAAAAAAAc6AYaAAAAIlJREFUeNpNydsSgzAIRVFstQeshtAk/P+nFrzMeF6YvaDYhGsGEPF7IloizIbaAbLuYqWoqiWAVpG6tdYGKkCx+G/NGdEJWKSWZua84wLLVvviAujPs835BCvj5dEacgM+0ackKGQXT+kzB4yCKnKKB8SNTulqPQRjQI7N3k2dANwwu/oTwOzOf5bwCzXxPgmEAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:compass",
    "name": "Compass",
    "category": "tools",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAm0lEQVQ4y82TyQnAIBREU4SQdOHJMkI68GQlVmNJdmMYYYLLZDnmwyD5zjzitiy/LOdcUfocTClVxRiL9/4aH0Hbul5mmKy1ndDDPASvDKtgMUaCOgg+VFgBCPkEOPa9AkII7wBs2h1kDGOfJgCaLLUUCB4IUAnIOVex8Ffs8SgRngDtMhhgiHeCRyjDLaQFjQDOv95IGkf98+Gdcg8P7woSafoAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:map",
    "name": "Map",
    "category": "tools",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAeElEQVQ4y2NgGBJg+QqP/yBMtuZXr47/v3V3FWmGwGwFafzz5xMYgwwiyhCYrTCNyBhkYHuH5X+ibcWGQWowDIFpxGUzuitQDCFFMywsMFwAEiBkCCw2cIYBPkNgtuLUjMsQEL37YDlhjdgMgWkkSTOyIWRppDsAABifRorVNHrHAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:spyglass",
    "name": "Spyglass",
    "category": "tools",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAKlBMVEUAAAD////04GNovb3ekjq9aigzkJCoX1igVhF+PzkeZWZVKSVTKwszFxLdsQeLAAAAAXRSTlMAQObYZgAAAFdJREFUeNpjQAWuARCaZZkphNGULAwW4nBaZuwAYrSoaGWBGZOEnFRANGeRSugBEGN6pWsMAwhsn70XLMDTu/sCWOBoxF0GsMDUHgYw4J15gQEC7qI5AABfeRR40g2q1AAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:lantern",
    "name": "Lantern",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAwCAMAAAAvgQplAAAAOVBMVEUAAAD//9X9/Yv4+H/5yWb2xWLzwFnwkUnvhEfsgUTDYyK9Xx+6XByLUjBJUGWBQCNCSl4+RFMlLD2L9Ii0AAAAAXRSTlMAQObYZgAAAJNJREFUeNrdkNEOwyAIRaUClrYq9P8/dnONCWTJHvbUlAdjbjhXc1Ky1iz5qb3X69bMUhoLc8XS+T77VsrWXVALYrmY0z4BwoLVd+ICWH3HQPpE/CtzzFQtBNqamvuYDkRnqQsi8qv0e/7xsYvswYcQSfBBkCn4oAwUfKxE61N8HCJH9MEcfTBkDj44AwcfA7mhjxek8xEfhQdTEwAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:soul_lantern",
    "name": "Soul Lantern",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAwCAMAAAAvgQplAAAAM1BMVEUAAAD/////+/v0+v/a/f/Z+vvE/f969fh08fVt7fEqyc8jwMYDlppJUGVCSl4+RFMlLD1Pln0gAAAAAXRSTlMAQObYZgAAAINJREFUeNrdkMsKxDAIRe1TTau3//+1gzNkUApddVHqIoSL5yYcIpiB8hhg/xtRLPQV0BHn3tqeA9tUtx9z4BvotKrlTl0ntdwRCDqSX+kDuKMEbuZIH/NAvJemoCJXpee5xUdjbsUHDzMXHzwPXHwE8l4fItWHjIsUH7KMUn2IPNHHB5WpED0+2mPjAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:golden_helmet",
    "name": "Golden Helmet",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAZUlEQVQ4y2NgGJ6gKVbsPzZMtOaXG0X/v3oXjoLvTBP+b6/H958ozX//l/0HARANMwAkTtAQkAEgxSCN6JphmCgDQBjZ7yBNINuJNgCmCR1TbABRYQCzhSwDYIZgUwQzhGEUYAAANYisw3NdQN0AAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:diamond_chestplate",
    "name": "Diamond Chestplate",
    "category": "combat",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAGFBMVEUAAAD///+h++hK7dkgxbUaqqcOPzYIJSASzXVWAAAAAXRSTlMAQObYZgAAAFNJREFUeNqNz0EOgEAIBEGkB/j/j806JmuMB/vE1I34Ua+eRx+J4T46QR3RSgxAqluAocSRmYBqwUx5Qs3Earxhwg0GbeAF8t5QuiqDZW/L1fevJzKqAlDbFhetAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:ender_eye",
    "name": "Eye of Ender",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAJ1BMVEUAAADL/N215FqX0WuIw1pxrEllm31XkUNOg4YxY2QeSDUQLDEbKxAqU3maAAAAAXRSTlMAQObYZgAAAF1JREFUeNpjwAo4V0HpGR0Q1oy0tMwFQJqrTcg1bRaIkai8PCwbyFiZZHWqNHMDkBHqBWWkVp1yjdwAUhyyOCIbpHhGamnrbCCDYWdHR+YGEIN758zdQArE2o1sMwC2eh5UbZUu5wAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:potion",
    "name": "Potion",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAbElEQVQ4y2NgGNTgSq7nfxBe6a76n3TNT7//P7N+KRxvPv+GNENAGkA2g/B0czHSDYAZAqJj+w/9JysMKDIAFAbIfJIMgWlG9zdRhuDSTLQhFBuAS2P32gvEBSguBUQbgE0RSZqRDUHHNMlwADOSe7Rn5KNOAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:blaze_rod",
    "name": "Blaze Rod",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAb0lEQVR42mNgoDfYnC35f3YY+3+yNK/Ilf7//7Pu/52TZf5PNWb4T7LN/3/UgTWvsyFRM9hmoOYb69T+748ix2aos0nWjOxn8jRD/UyRs0kOMLDmgwwUhPaA2LwxWoD80IbZTlYigQFQuibZ2dQCAG4MefYDQI0dAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:quartz",
    "name": "Quartz",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEUAAAD39fLq5d7l39bd1MbUyrq2pI6zoJGJe3NvXVoXLlaWAAAAAXRSTlMAQObYZgAAAHZJREFUeNpjAAH2cgYIKFKH8NiVJEAMpYYiRQ8wQ6JQOALEEDQtNskoB7KazUpMm8WBDI5wF7NWC6BURbqL29QJQIZ6e0jYtPICBg6htpDMdGMgI1AjNLNVtIGBMzQyLDM1k4GBYWrmtMy0CUAG5wTOCTMZEAAAopcbEHF0A/MAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:chorus_fruit",
    "name": "Chorus Fruit",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEUAAAD39Pfh1+G6m7qjgaKOZ414WXhlSGReLlw6FDo7QZHlAAAAAXRSTlMAQObYZgAAAFpJREFUeNpjwAqYYZQylKEoXF4AZhkKh6Y3gBhGyiWulWA58zbXDBCjvCwkNXwCAwN7SIpraDqIkZoWGl4+ASSVnhpWAWK0V6SVd4IUc3a0gwUYGGbOnIlkMwCdRhYPhZ6m1wAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:bone",
    "name": "Bone",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAElBMVEUAAAD///38++3o5dLLxqV7fmuVDo9QAAAAAXRSTlMAQObYZgAAAEBJREFUeNpjQAUsJlCGs2oAhOEkZAplKLtClCiFBkAEVBmgAgEMKAIuUAFjQYgAs6JgANR0YahSVxMogyEU1QEAGS0HkMqcmpYAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:clay_ball",
    "name": "Clay Ball",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAG1BMVEUAAACvudasrr2hp7GUmaR1fZBebI1ARFo3OUQcuTmNAAAAAXRSTlMAQObYZgAAAEtJREFUeNpjwA/KyyE0e3BoAZhRYmIaARYwNBJObQAxjB2NwYxiJ0HXMJBcibGJMZhRaixkFpoBUpNsHBrWANLWEZraATGxowOrhQD+ng/8MnX9UgAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:glowstone_dust",
    "name": "Glowstone Dust",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAGFBMVEUAAAD51Jz/vF7rqk60cUCOVi5+SCFaORxHN0c3AAAAAXRSTlMAQObYZgAAAElJREFUeNpjwA/YEqCMZDWogKJKAZiRJGToDhZQUlRJAQklC5kIO4aDZIyETNxAciWKzs4uIBF2J5MUZ7C28hDXcgYwKC/HaiEA2vEMUqfTCnYAAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:prismarine_crystals",
    "name": "Prismarine Crystals",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAdElEQVQ4jWNgGL6gaMmM/zBMluYtN079v//yDpgmyTDPlBi4ZnQMEgfJk2QIiAbhiUe3gzFRBiA7GYRBmmCYZP+DNKEbSJRmGIYZAHI+TA6rIdg0w/yMrBnZYAwDkBWia0YOTKxhAVOMHNq4MFb/E6VoUAIA+dsNV6rGpd8AAAAASUVORK5CYII="
  },
  {
    "id": "minecraft:end_portal_frame",
    "name": "End Portal Frame",
    "category": "blocks",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAHlBMVEXt8rnk5qzAwoeZxpO1r3lCc2cvWE4kQzsGGRQDEg4NqstBAAAAbUlEQVR42mMIhQKG4PJi9yTzclOG8CDXJNEQ1VSGcAeR0DRHFiDDMSw9vUwEyFConDlzKlMqQ7BCZkdHG5MpQxiI0coElgIyYFKtICmYSLhjampomAjYwDCQgSArElVBVgSnJaulmKWZMsCcAQDP4imZv+L1CAAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:gold_ingot",
    "name": "Gold Ingot",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAG1BMVEUAAAD//////eD99V/61krpsRXclhOyZBF1KALSidGuAAAAAXRSTlMAQObYZgAAAFpJREFUeNpjwAHKIRR7uUsBmFtsbGwO4jobGxubNDAUGYOAkgVDibKxsZGSmQdDiZGxknJYGpBhImSalhbiwVBqAqYbGNhDTNNCOxoYGBhKXSM6IOZWNGC3FwCLuxUEBRwUswAAAABJRU5ErkJggg=="
  },
  {
    "id": "minecraft:iron_ingot",
    "name": "Iron Ingot",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAhElEQVQ4y9WSwQnAIBAEbcpefFmEJViNJdmNYQ82OeVUzCdkYfEgzhhinPtNYowNfQWhpRRpSqkdQbXWrqZkBy0lgJAdxDKYRcJTVxIdgmC8949glIxQzllAFLMpoMSCWL33FtDID7gC8QygwPoWKLFeV0MdOF4lJVhDCHto9hMdQZ/nAqzufev6TWmcAAAAAElFTkSuQmCC"
  },
  {
    "id": "minecraft:copper_ingot",
    "name": "Copper Ingot",
    "category": "items",
    "dataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAG1BMVEUAAAD7w7b8mYLnfFbBWjacTjGcRSmKQSltNCFALkIDAAAAAXRSTlMAQObYZgAAAF9JREFUeNpjwAHSIBRbmksBmJvsGmIO4jqbhDqbFDAkORu7hhgrmTMkK5u4GCm5RjAkOxkrKbuEAxkhQq4hruUeDMmhKqFAgQYGNlfVENeOBgYGhlRTjw6IuRkN2O0FAIf/FK7CRf/vAAAAAElFTkSuQmCC"
  }
];

export function getItemDefinition(itemId: string): MinecraftItemDef {
  const found = MINECRAFT_ITEMS.find(i => i.id === itemId);
  return found || MINECRAFT_ITEMS[0];
}

export function getItemDataUrl(itemId: string): string {
  return getItemDefinition(itemId).dataUrl;
}

export function getItemsByCategory(category: string): MinecraftItemDef[] {
  return MINECRAFT_ITEMS.filter(i => i.category === category);
}
