import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { CreateInstancePayload, InstanceMetadata } from '../../types';
import { InstanceMetadataStore } from './metadata';
import { PathManager } from '../storage/paths';
import {
  resolveVersionConfig,
  generateBuildGradle,
  generateGradleProperties,
  generateSettingsGradle,
  getGradleDistributionUrl
} from './fabricVersions';
import { JavaDetector } from '../java/javaDetector';
import { MinecraftCompatibilityResolver } from './minecraftCompatibilityResolver';
import { LogStreamer } from '../processes/logStreamer';

const EMBEDDED_GRADLEW_BAT = "@rem\n@rem Copyright 2015 the original author or authors.\n@rem\n@rem Licensed under the Apache License, Version 2.0 (the \"License\");\n@rem you may not use this file except in compliance with the License.\n@rem You may obtain a copy of the License at\n@rem\n@rem      https://www.apache.org/licenses/LICENSE-2.0\n@rem\n@rem Unless required by applicable law or agreed to in writing, software\n@rem distributed under the License is distributed on an \"AS IS\" BASIS,\n@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n@rem See the License for the specific language governing permissions and\n@rem limitations under the License.\n@rem\n@rem SPDX-License-Identifier: Apache-2.0\n@rem\n\n@if \"%DEBUG%\"==\"\" @echo off\n@rem ##########################################################################\n@rem\n@rem  Gradle startup script for Windows\n@rem\n@rem ##########################################################################\n\n@rem Set local scope for the variables, and ensure extensions are enabled\nsetlocal EnableExtensions\n\nset DIRNAME=%~dp0\nif \"%DIRNAME%\"==\"\" set DIRNAME=.\n@rem This is normally unused\nset APP_BASE_NAME=%~n0\nset APP_HOME=%DIRNAME%\n\n@rem Resolve any \".\" and \"..\" in APP_HOME to make it shorter.\nfor %%i in (\"%APP_HOME%\") do set APP_HOME=%%~fi\n\n@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.\nset DEFAULT_JVM_OPTS=\"-Xmx64m\" \"-Xms64m\"\n\n@rem Find java.exe\nif defined JAVA_HOME goto findJavaFromJavaHome\n\nset JAVA_EXE=java.exe\n%JAVA_EXE% -version >NUL 2>&1\nif %ERRORLEVEL% equ 0 goto execute\n\necho. 1>&2\necho ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. 1>&2\necho. 1>&2\necho Please set the JAVA_HOME variable in your environment to match the 1>&2\necho location of your Java installation. 1>&2\n\n\"%COMSPEC%\" /c exit 1\n\n:findJavaFromJavaHome\nset JAVA_HOME=%JAVA_HOME:\"=%\nset JAVA_EXE=%JAVA_HOME%\\bin\\java.exe\n\nif exist \"%JAVA_EXE%\" goto execute\n\necho. 1>&2\necho ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME% 1>&2\necho. 1>&2\necho Please set the JAVA_HOME variable in your environment to match the 1>&2\necho location of your Java installation. 1>&2\n\n\"%COMSPEC%\" /c exit 1\n\n:execute\n@rem Setup the command line\n\nset CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar\n\n\n@rem Execute Gradle\n\"%JAVA_EXE%\" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% \"-Dorg.gradle.appname=%APP_BASE_NAME%\" -classpath \"%CLASSPATH%\" org.gradle.wrapper.GradleWrapperMain %*\n";

const EMBEDDED_GRADLEW_SH = "#!/bin/sh\n\n##############################################################################\n#\n#   Gradle start up script for POSIX generated by Gradle.\n#\n##############################################################################\n\n# Attempt to set APP_HOME\n# Resolve links: $0 may be a link\nPRG=\"$0\"\n# Need this for relative symlinks.\nwhile [ -h \"$PRG\" ] ; do\n    ls=`ls -ld \"$PRG\"`\n    link=`expr \"$ls\" : '.*-> \\(.*\\)$'`\n    if expr \"$link\" : '/.*' > /dev/null; then\n        PRG=\"$link\"\n    else\n        PRG=`dirname \"$PRG\"`\"/$link\"\n    fi\ndone\nSAVED=\"`pwd`\"\ncd \"`dirname \"$PRG\"`/\" >/dev/null\nAPP_HOME=\"`pwd -P`\"\ncd \"$SAVED\" >/dev/null\n\nAPP_NAME=\"Gradle\"\nAPP_BASE_NAME=`basename \"$0\"\"\n\n# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.\nDEFAULT_JVM_OPTS='\"-Xmx64m\" \"-Xms64m\"'\n\n# Use the maximum available, or set MAX_FD != -1 to use that value.\nMAX_FD=\"maximum\"\n\nwarn () {\n    echo \"$*\"\n}\n\ndie () {\n    echo\n    echo \"$*\"\n    echo\n    exit 1\n}\n\n# OS specific support (must be 'true' or 'false').\ncygwin=false\nmsys=false\ndarwin=false\nnonstop=false\ncase \"`uname`\" in\n  CYGWIN* )\n    cygwin=true\n    ;;\n  Darwin* )\n    darwin=true\n    ;;\n  MINGW* )\n    msys=true\n    ;;\n  NONSTOP* )\n    nonstop=true\n    ;;\nesac\n\nCLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar\n\n\n# Determine the Java command to use to start the JVM.\nif [ -n \"$JAVA_HOME\" ] ; then\n    if [ -x \"$JAVA_HOME/jre/sh/java\" ] ; then\n        # IBM's JDK on AIX uses strange locations for the executables\n        JAVACMD=\"$JAVA_HOME/jre/sh/java\"\n    else\n        JAVACMD=\"$JAVA_HOME/bin/java\"\n    fi\n    if [ ! -x \"$JAVACMD\" ] ; then\n        die \"ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation.\"\n    fi\nelse\n    JAVACMD=java\n    which java >/dev/null 2>&1 || die \"ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation.\"\nfi\n\n# Increase the maximum file descriptors if we can.\nif [ \"$cygwin\" = \"false\" -a \"$darwin\" = \"false\" -a \"$nonstop\" = \"false\" ] ; then\n    MAX_FD_LIMIT=`ulimit -H -n`\n    if [ $? -eq 0 ] ; then\n        if [ \"$MAX_FD\" = \"maximum\" -o \"$MAX_FD\" = \"max\" ] ; then\n            MAX_FD=\"$MAX_FD_LIMIT\"\n        fi\n        ulimit -n $MAX_FD\n        if [ $? -ne 0 ] ; then\n            warn \"Could not set maximum file descriptor limit: $MAX_FD\"\n        fi\n    else\n        warn \"Could not query maximum file descriptor limit: $MAX_FD_LIMIT\"\n    fi\nfi\n\n# For Darwin, add options to specify how the application appears in the dock\nif $darwin; then\n    GRADLE_OPTS=\"$GRADLE_OPTS \\\"-Xdock:name=$APP_NAME\\\" \\\"-Xdock:icon=$APP_HOME/media/gradle.icns\\\"\"\nfi\n\n# For Cygwin or MSYS, switch paths to Windows format before running java\nif [ \"$cygwin\" = \"true\" -o \"$msys\" = \"true\" ] ; then\n    APP_HOME=`cygpath --path --mixed \"$APP_HOME\"`\n    CLASSPATH=`cygpath --path --mixed \"$CLASSPATH\"`\n    JAVACMD=`cygpath --unix \"$JAVACMD\"`\n    # We build the pattern for arguments to be converted via cygpath\n    ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`\n    SEP=\"\"\n    for dir in $ROOTDIRSRAW ; do\n        ROOTDIRS=\"$ROOTDIRS$SEP$dir\"\n        SEP=\"|\"\n    done\n    OURCYGPATTERN=\"(^($ROOTDIRS))\"\n    # Add a user-defined pattern to the cygpath arguments\n    if [ \"$GRADLE_CYGPATTERN\" != \"\" ] ; then\n        OURCYGPATTERN=\"$OURCYGPATTERN|($GRADLE_CYGPATTERN)\"\n    fi\n    # Now convert the arguments - kludge to limit ourselves to /bin/sh\n    i=0\n    for arg in \"$@\" ; do\n        CHECK=`echo \"$arg\"|egrep -c \"$OURCYGPATTERN\" -`\n        CHECK2=`echo \"$arg\"|egrep -c \"^-\"`                                 ### Determine if an option\n        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition\n            eval `echo args$i`=`\"\\\"$arg\"\"\"`   \n            eval `echo args${i}true`   \n            i=$((i+1))\n        else\n            eval `echo args$i`=`\"\\\"$arg\\\"\"`   \n            i=$((i+1))\n        fi\n    done\n    case $i in\n        0) set -- ;;\n        1) set -- \"$args0\" ;;\n        2) set -- \"$args0\" \"$args1\" ;;\n        3) set -- \"$args0\" \"$args1\" \"$args2\" ;;\n        4) set -- \"$args0\" \"$args1\" \"$args2\" \"$args3\" ;;\n        5) set -- \"$args0\" \"$args1\" \"$args2\" \"$args3\" \"$args4\" ;;\n        6) set -- \"$args0\" \"$args1\" \"$args2\" \"$args3\" \"$args4\" \"$args5\" ;;\n        7) set -- \"$args0\" \"$args1\" \"$args2\" \"$args3\" \"$args4\" \"$args5\" \"$args6\" ;;\n        8) set -- \"$args0\" \"$args1\" \"$args2\" \"$args3\" \"$args4\" \"$args5\" \"$args6\" \"$args7\" ;;\n        9) set -- \"$args0\" \"$args1\" \"$args2\" \"$args3\" \"$args4\" \"$args5\" \"$args6\" \"$args7\" \"$args8\" ;;\n    esac\nfi\n\n# Escape application args\nsave () {\n    local i=\"$*\"\\n    [ -z \"$i\" ] || echo $i\n}\nAPP_ARGS=`save \"$@\"`\n\n# Collect all arguments for the java command, following the shell quoting and substitution rules\neval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \"-Dorg.gradle.appname=$APP_BASE_NAME\" -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain \"$APP_ARGS\"\n\nexec \"$JAVACMD\" \"$@\"\n";

const EMBEDDED_WRAPPER_JAR_BASE64 = "UEsDBBQACAgIAAAAIQAAAAAAAAAAAAAAAAAQAAkATUVUQS1JTkYvTElDRU5TRVVUBQABAAAAAN1aW3PbNhZ+z6/AaGZn7BlGSbvt7rZ9UmOnVTeVM5K9mT5CJChhQxIsQFrW/vo9F9woyU72dT2Z1qKJg4Nz+c53DvRKfOln0ctyr8QHXarOqVcvvPkvZZ02nfh2/rYQv8lulPYovn379rtnF+2Hof/xzZvD4TCXtM3c2N2bhrdyb17hwvvb9e8bsVjdiHd3q5vl/fJutRHv79biYXNbiPXtx/XdzcM7fFzQWzfLzf16+fMDPiEB38zFjap1pwdQzs1feW1m/kQz4fayaUSrZCcGOOmgbOuE7CpRmq7iVaI2VoxOFcKq3ppqLPFx4UXhu5V2g9XbEZ8L6USFW6pKbI9io0oW8g3It2bc7cUPwtTwQcN7phxb1Q2nehl7plhp+qPVu/0gzKFTVoBKsFAPRyHHYW+s/g/t5+VcWjHs5SBg052VsLDb0UveDpkCaicbcUuiz5QYOzwgaa+ELElK0ALMAO96MQZe8Apq5XhrMOhgTVMIaVX40JDSBZ4Gn45dBctK07am85L8i+Kghz3L4Q3n4r2xpEc/2t5AxCSrRocHH828lBkdxYkrfc1LzUHZAtxnwUuohO7490IMRpQSnI7veSn8J7KAFa3s5E6h83BfN5Z7r1ghDntFxwfv076SZOeWOWiMJpBypUETco/b6x4l1boGa/bKlij66vu3f7mm7QyYhw0fBI2DG8Dq6ANwk1UuSASRW9WBEUoNrpxIz/RMLv/DjDNxBWvxNzu7zr0O/9Amj7oaUZYVeXx4AeoJtNUOFQG9W+0cBTzFGScBueUs1DawWwkpCOnVnkZab1WtrIXl9NeaLP4Zt2hNpeFokrIqOFh3ZTOSKSAJRWcG0ehW4+7gR2fq4YDh5WhDcEoF1g+5R4K8GH6hCPlf691o6e/glkZl8HG3/TeEwrnqsjvyM3DH2FB+1Na08MdyLzvQOiQIREXn8E0ZAoqeNP5jLaRg85C4YnpAL+PkmJA2vcaEMqScP+YOIgHOAI8nB87RC076yOjtUA7nbqsqLcVw7PNjfzL28xkoHOAhaUw4hJGWUkB34RgxAdh0/litrABIHqVu5LYJ+Z/hUoFoigFYSh9KMuJCQDcwA7wc4Y0tBS9rMqscBqwtZKGgrRdxBQdQT7LtYWdYCNAOYc4L8c1F3yvY+QmSqTGH62SFG2X1I1jxUQk0iJudRgDucdkG/vReEtsgKL6VDp3XUSpWuAdGP0QPYxVuRe7CXDjsdbnPwACcNUANgMy06lGTKzGKwTQ+T4QCCxsbPoEI7+Y8m7wwrHLKQaSQ9SVsZhpKClimd7qDXc59fo7HAafqSfoX4tR83noYzd53JN5XDataqWN+ql5aihS0Cx2jVVY1R8iD7jMZbgvRgnHSyVZdB6drACJby5KKRJHVyGjUM6XQOsrUyevvEMp9jb/o8dMciCmb7RcN6BMu1NKoBwqb+IRiuPJMJEgybBtaBX9/TvkiS4oBUd/A1k2AbTduATs8eATeQdFFmpN6PhVoI8LxM1oRvEzl7sVqkRMVRGXaHuN9q8CYNZjiefLyddVezOKZZl4W1/sIy7BINZCA1gAYF+iFrWwojg4W13VEPsbOW19gFuRGV8lQaKfBpWQh+7vixVIUsSvfA/4lnQARdYOLG6CUIC0rWZEKuaMbVOtyCIeaOyosISXVSP8Gux8rH7OVyLVyoxcZjEyiILM22g04bjk6qvK0Y0t46WnkJ0K8VJrUUzDC9KwhHuEortflaEYHydtK+xmhzyZ2FCiXcnrXEfZDKKKPyLAXIxHBarYCe0uR5+p8dp7CJ/w6Hjtk4BcpT25AxMf2ZFOxB2W2CuIJKKMiJAel831SEjr15wjx0+C2pQF7c7lGwpulHwPRt3PxC9Iq3PZdPH5gVmIzcnH";

export class LoomProjectGenerator {
  public static async generateProject(
    targetDir: string,
    payload: CreateInstancePayload,
    instanceId?: string
  ): Promise<InstanceMetadata> {
    PathManager.ensureDirectory(targetDir);

    const metadata = InstanceMetadataStore.createDefaultMetadata(payload, instanceId);
    const mcVersion = metadata.minecraft.version;
    
    const compatibility = MinecraftCompatibilityResolver.resolveCompatibility(mcVersion);
    const versionSpec = resolveVersionConfig(mcVersion);

    const cleanProjectName = PathManager.sanitizeFilename(metadata.name)
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '');

    const subdirs = [
      'mods',
      'resourcepacks',
      'shaderpacks',
      'config',
      'saves',
      'logs',
      'screenshots',
      'gradle/wrapper',
      'src/main/resources'
    ];
    for (const dir of subdirs) {
      PathManager.ensureDirectory(path.join(targetDir, dir));
    }

    fs.writeFileSync(
      path.join(targetDir, 'settings.gradle'),
      generateSettingsGradle(mcVersion, cleanProjectName),
      'utf-8'
    );

    fs.writeFileSync(
      path.join(targetDir, 'gradle.properties'),
      generateGradleProperties(mcVersion, cleanProjectName, metadata.runtime.memoryMb || 4096),
      'utf-8'
    );

    fs.writeFileSync(
      path.join(targetDir, 'build.gradle'),
      generateBuildGradle(mcVersion, cleanProjectName, metadata.runtime.memoryMb || 4096),
      'utf-8'
    );

    const fabricModJson: Record<string, any> = {
      schemaVersion: 1,
      id: 'voxelplus_instance',
      version: '1.0.0',
      name: metadata.name,
      description: 'Voxel+ Fabric instance. Drop mods into the mods/ folder.',
      authors: ['Voxel+'],
      contact: {},
      license: 'MIT',
      environment: 'client',
      depends: {
        fabricloader: `>=${versionSpec.loaderVersion}`,
        minecraft: `~${mcVersion}`
      }
    };
    fs.writeFileSync(
      path.join(targetDir, 'src/main/resources/fabric.mod.json'),
      JSON.stringify(fabricModJson, null, 2),
      'utf-8'
    );

    const gradleWrapperProps = `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=${getGradleDistributionUrl(mcVersion)}
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`;
    fs.writeFileSync(
      path.join(targetDir, 'gradle/wrapper/gradle-wrapper.properties'),
      gradleWrapperProps,
      'utf-8'
    );

    this.ensureWrapperFiles(targetDir);

    InstanceMetadataStore.writeMetadata(targetDir, metadata);

    this.preDownloadDependencies(targetDir, metadata.id, metadata.name, mcVersion, compatibility)
      .catch(err => console.warn('[LoomGenerator] Pre-download error:', err));

    return metadata;
  }

  private static ensureWrapperFiles(targetDir: string): void {
    const destBat = path.join(targetDir, 'gradlew.bat');
    const destSh = path.join(targetDir, 'gradlew');
    const destJar = path.join(targetDir, 'gradle/wrapper/gradle-wrapper.jar');

    const templateBase = path.resolve(__dirname, '../../../templates');
    const tBat = path.join(templateBase, 'gradlew.bat');
    const tSh = path.join(templateBase, 'gradlew');
    const tJar = path.join(templateBase, 'gradle/wrapper/gradle-wrapper.jar');

    if (fs.existsSync(tBat)) {
      fs.copyFileSync(tBat, destBat);
    } else {
      fs.writeFileSync(destBat, EMBEDDED_GRADLEW_BAT, 'utf-8');
    }

    if (fs.existsSync(tSh)) {
      fs.copyFileSync(tSh, destSh);
    } else {
      fs.writeFileSync(destSh, EMBEDDED_GRADLEW_SH, 'utf-8');
    }

    if (fs.existsSync(tJar)) {
      fs.copyFileSync(tJar, destJar);
    } else {
      const jarBuf = Buffer.from(EMBEDDED_WRAPPER_JAR_BASE64, 'base64');
      fs.writeFileSync(destJar, jarBuf);
    }
  }

  private static async preDownloadDependencies(
    instanceDir: string,
    instanceId: string,
    instanceName: string,
    mcVersion: string,
    compatibility: any
  ): Promise<void> {
    const javaList = await JavaDetector.scanSystemJava();
    const resolvedEnv = MinecraftCompatibilityResolver.resolveEnvironment(mcVersion, javaList);

    if (!resolvedEnv.isCompatible || !resolvedEnv.javaRuntime) {
      LogStreamer.addLog(
        `[Voxel+ Setup] No compatible Java ${compatibility.java.recommended} found. Instance will need Java installed before launch.`,
        'WARN', instanceId, instanceName
      );
      return;
    }

    LogStreamer.addLog(
      `[Voxel+ Setup] Pre-downloading Minecraft ${mcVersion} assets and Fabric Loom dependencies...`,
      'INFO', instanceId, instanceName
    );

    const env: NodeJS.ProcessEnv = {
      ...process.env,
      JAVA_HOME: resolvedEnv.javaHome || undefined,
      PATH: `${path.join(resolvedEnv.javaHome || '', 'bin')};${process.env.PATH || ''}`
    };

    const gradlewBat = path.join(instanceDir, 'gradlew.bat');
    if (!fs.existsSync(gradlewBat)) {
      LogStreamer.addLog('[Voxel+ Setup] gradlew.bat missing, writing fallback wrapper...', 'WARN', instanceId, instanceName);
      fs.writeFileSync(gradlewBat, EMBEDDED_GRADLEW_BAT, 'utf-8');
    }

    return new Promise<void>((resolve) => {
      const comspec = process.env.ComSpec || 'cmd.exe';
      const child = spawn(
        comspec,
        ['/d', '/c', 'gradlew.bat dependencies --no-daemon'],
        {
          cwd: instanceDir,
          env,
          windowsHide: true,
          shell: true
        }
      );

      if (child.stdout) {
        child.stdout.on('data', (data: Buffer) => {
          const lines = data.toString().split(/\r?\n/).filter((l: string) => l.trim());
          for (const line of lines) {
            LogStreamer.addLog(line, 'INFO', instanceId, instanceName);
          }
        });
      }

      if (child.stderr) {
        child.stderr.on('data', (data: Buffer) => {
          const lines = data.toString().split(/\r?\n/).filter((l: string) => l.trim());
          for (const line of lines) {
            LogStreamer.addLog(line, 'WARN', instanceId, instanceName);
          }
        });
      }

      child.on('close', (code: number | null) => {
        if (code === 0) {
          LogStreamer.addLog(
            `[Voxel+ Setup] Dependencies downloaded. Minecraft ${mcVersion} is ready to launch.`,
            'INFO', instanceId, instanceName
          );
        } else {
          LogStreamer.addLog(
            `[Voxel+ Setup] Dependency download exited with code ${code}. Check network connection and try launching - Gradle will retry.`,
            'WARN', instanceId, instanceName
          );
        }
        resolve();
      });

      child.on('error', (err: Error) => {
        LogStreamer.addLog(`[Voxel+ Setup] Pre-download error: ${err.message}`, 'WARN', instanceId, instanceName);
        resolve();
      });
    });
  }
}
